n_units: 16
n_layers: 3
dropout: 0.05
out_act_f: "sigmoid"
out_clipping_x_min: -1.0
out_clipping_x_max: 1.0
out_clipping_p: 10

hidden_layer_fn: "selu_mc_dropout"
optimizer: "Adam"

batch_size: 32
epochs: 50