    "signal_pe_ratio_max": ["standard"]
    "signal_ratio_max": ["standard"]
    "snr_min": ["standard"]
    "snr_max": ["standard"]
    "snr_average": ["standard"]
    "max_tail_ratio": ["standard"]
    "average_tail_ratio": ["standard"]
    "max_head_ratio": ["standard"]
    "snr_average_0.1_0.2": ["standard"]
    "snr_average_0.2_0.5": ["standard"]
    "snr_average_0.5_1.0": ["standard"]
    "snr_average_1.0_2.0": ["standard"]
    "snr_average_2.0_5.0": ["standard"]
    "snr_average_5.0_10.0": ["standard"]
    "fas_ratio_low": ["standard"]
    "fas_ratio_high": ["standard"]
    "pn_pga_ratio": ["standard"]
    "is_vertical": null
    "spike_detector": ["standard"]
    "jerk_detector": ["standard"]
    "lowres_detector": ["standard"]
    "gainjump_detector": ["standard"]
    "flatline_detector": ["standard"]
    "p_numpeaks_detector": ["standard"]
    "p_multimax_detector": ["standard"]
    "p_multidist_detector": ["standard"]
    "s_numpeaks_detector": ["standard"]
    "s_multimax_detector": ["standard"]
    "s_multidist_detector": ["standard"]